# Generated by Django 4.2.8 on 2024-01-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialSite', '0003_remove_post_is_mod_altered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
