# Generated by Django 4.2.9 on 2024-01-16 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='webpage',
            field=models.URLField(blank=True, default='None', max_length=500, null=True, validators=[django.core.validators.ProhibitNullCharactersValidator(), django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
